name: release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin

    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v3
        with: 
          go-version: 1.18
          
      - name: build
        run: go build -o telereto-${{ matrix.goos }}-${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: release
        id: upload-release-asset 
        uses: softprops/action-gh-release@v1
        with:
          files: ./telereto-${{ matrix.goos }}-${{ matrix.goarch }}
